/**
 * seed-datajud.mjs — DataJud CNJ integration demo data.
 *
 * Populates: datajud_case_details, datajud_legal_subjects,
 *            datajud_case_participants, datajud_timeline_events, datajud_sync_log
 *
 * All data mirrors what the real DataJud public Elasticsearch API returns
 * (POST api_publica_{court}/_search → hits.hits[]._source).
 *
 * Movement IDs use the composite format: "{codigo}_{dataHora}" — same
 * format generated by the enrichment service from real API responses.
 */

import {
  FIRM_A_ID, FIRM_B_ID,
  dateOnly, daysAgo, timestampAt,
  upsertRows, replaceRows, log,
} from './_shared.mjs';

export async function seed(supabase, ctx) {
  const mod = 'seed-datajud';
  let total = 0;

  try {
    const A = ctx.firmAUsers;
    const B = ctx.firmBUsers;

    // ------------------------------------------------------------------
    // 1. DataJud Case Details
    //    Each row represents a successful enrichment from the real API.
    //    Fields match _source from the Elasticsearch response.
    // ------------------------------------------------------------------
    const caseDetails = [
      // ── Firm A ─────────────────────────────────────────────────────
      // Case A1 — Cível (TJSP) · 1234567-89.2025.8.26.0100 → tjsp
      {
        id: 'b8000001-0001-4001-8001-b80000010001', law_firm_id: FIRM_A_ID,
        matter_id: 'a0000001-0001-4001-8001-a00000010001',
        datajud_case_id: 'ES_TJSP_a0001',  // Elasticsearch _id
        numero_processo_cnj: '1234567-89.2025.8.26.0100',
        tribunal_alias: 'TJSP',
        court_instance: 1,
        court_code: 100,
        court_name: '5ª Vara Cível do Foro Central',
        court_municipality_ibge: 3550308,
        court_municipality: 'São Paulo',
        court_state: 'SP',
        court_competence: 'Cível',
        process_class_code: 7,
        process_class_name: 'Procedimento Comum Cível',
        process_format_code: 2,
        process_format_name: 'Eletrônico',
        court_system_code: 102,
        court_system_name: 'SAJ - Sistema de Automação da Justiça',
        filing_date: dateOnly(-120),
        last_update_date: dateOnly(-3),
        case_value: 150000.00,
        is_confidential: false,
        enrichment_confidence: 0.92,
        enrichment_status: 'completed',
        last_enrichment_at: daysAgo(1),
        data_conflicts: null,
        created_by: A.admin,
      },
      // Case A2 — Trabalhista (TRT2) · 9876543-21.2025.5.02.0001 → trt2
      {
        id: 'b8000001-0002-4001-8001-b80000010002', law_firm_id: FIRM_A_ID,
        matter_id: 'a0000001-0002-4001-8001-a00000010002',
        datajud_case_id: 'ES_TRT2_a0002',
        numero_processo_cnj: '9876543-21.2025.5.02.0001',
        tribunal_alias: 'TRT2',
        court_instance: 1,
        court_code: 1,
        court_name: '2ª Vara do Trabalho de São Paulo',
        court_municipality_ibge: 3550308,
        court_municipality: 'São Paulo',
        court_state: 'SP',
        court_competence: 'Trabalhista',
        process_class_code: 1116,
        process_class_name: 'Reclamação Trabalhista - Rito Ordinário',
        process_format_code: 2,
        process_format_name: 'Eletrônico',
        court_system_code: 101,
        court_system_name: 'PJe - Processo Judicial Eletrônico',
        filing_date: dateOnly(-90),
        last_update_date: dateOnly(-5),
        case_value: 85000.00,
        is_confidential: false,
        enrichment_confidence: 0.88,
        enrichment_status: 'completed',
        last_enrichment_at: daysAgo(1),
        data_conflicts: null,
        created_by: A.admin,
      },
      // Case A3 — Criminal (TJSP) · 5555666-77.2025.8.26.0001 → tjsp
      // Includes a data conflict for demo (court_name mismatch)
      {
        id: 'b8000001-0003-4001-8001-b80000010003', law_firm_id: FIRM_A_ID,
        matter_id: 'a0000001-0003-4001-8001-a00000010003',
        datajud_case_id: 'ES_TJSP_a0003',
        numero_processo_cnj: '5555666-77.2025.8.26.0001',
        tribunal_alias: 'TJSP',
        court_instance: 1,
        court_code: 1,
        court_name: '3ª Vara Criminal do Foro Central',
        court_municipality_ibge: 3550308,
        court_municipality: 'São Paulo',
        court_state: 'SP',
        court_competence: 'Criminal',
        process_class_code: 283,
        process_class_name: 'Ação Penal - Procedimento Ordinário',
        process_format_code: 2,
        process_format_name: 'Eletrônico',
        court_system_code: 102,
        court_system_name: 'SAJ - Sistema de Automação da Justiça',
        filing_date: dateOnly(-60),
        last_update_date: dateOnly(-2),
        case_value: 0,
        is_confidential: true,
        enrichment_confidence: 0.78,
        enrichment_status: 'completed',
        last_enrichment_at: daysAgo(2),
        data_conflicts: {
          conflicts: [
            {
              field_name: 'court_name',
              existing_value: '3ª Vara Criminal - SP',
              datajud_value: '3ª Vara Criminal do Foro Central',
              conflict_type: 'value_mismatch',
              resolution_strategy: 'prefer_datajud',
              confidence_impact: -0.1,
            },
          ],
        },
        created_by: A.admin,
      },

      // ── Firm B ─────────────────────────────────────────────────────
      // Case B1 — Imobiliário (TJRJ) · 1111222-33.2026.8.19.0001 → tjrj
      {
        id: 'b8000002-0001-4001-8001-b80000020001', law_firm_id: FIRM_B_ID,
        matter_id: 'b6b6b6b6-0001-0001-0001-b6b6b6b6b6b6',
        datajud_case_id: 'ES_TJRJ_b0001',
        numero_processo_cnj: '1111222-33.2026.8.19.0001',
        tribunal_alias: 'TJRJ',
        court_instance: 1,
        court_code: 1,
        court_name: '4ª Vara Cível da Comarca da Capital',
        court_municipality_ibge: 3304557,
        court_municipality: 'Rio de Janeiro',
        court_state: 'RJ',
        court_competence: 'Cível',
        process_class_code: 7,
        process_class_name: 'Procedimento Comum Cível',
        process_format_code: 2,
        process_format_name: 'Eletrônico',
        court_system_code: 101,
        court_system_name: 'PJe - Processo Judicial Eletrônico',
        filing_date: dateOnly(-90),
        last_update_date: dateOnly(-4),
        case_value: 320000.00,
        is_confidential: false,
        enrichment_confidence: 0.90,
        enrichment_status: 'completed',
        last_enrichment_at: daysAgo(1),
        data_conflicts: null,
        created_by: B.admin,
      },
      // Case B2 — Tributário Federal (TRF2) · 3333444-55.2026.4.02.5101 → trf2
      {
        id: 'b8000002-0002-4001-8001-b80000020002', law_firm_id: FIRM_B_ID,
        matter_id: 'b0000001-0003-4001-8001-b00000010003',
        datajud_case_id: 'ES_TRF2_b0002',
        numero_processo_cnj: '3333444-55.2026.4.02.5101',
        tribunal_alias: 'TRF2',
        court_instance: 1,
        court_code: 5101,
        court_name: '6ª Vara Federal Fiscal do Rio de Janeiro',
        court_municipality_ibge: 3304557,
        court_municipality: 'Rio de Janeiro',
        court_state: 'RJ',
        court_competence: 'Tributária',
        process_class_code: 120,
        process_class_name: 'Mandado de Segurança Cível',
        process_format_code: 2,
        process_format_name: 'Eletrônico',
        court_system_code: 103,
        court_system_name: 'eProc - Processo Eletrônico Federal',
        filing_date: dateOnly(-30),
        last_update_date: dateOnly(-1),
        case_value: 450000.00,
        is_confidential: false,
        enrichment_confidence: 0.95,
        enrichment_status: 'completed',
        last_enrichment_at: daysAgo(0, 6), // today, 6 hours ago
        data_conflicts: null,
        created_by: B.admin,
      },
    ];
    // Use replaceRows: delete existing data for both firms first, then insert.
    // Child tables (legal_subjects, participants, timeline_events) cascade-delete.
    let r = await replaceRows(supabase, 'datajud_case_details', 'law_firm_id', [FIRM_A_ID, FIRM_B_ID], caseDetails);
    if (r.error) throw new Error(`datajud_case_details: ${r.error.message}`);
    total += r.count;
    log(`datajud_case_details: ${r.count} rows`);

    // ------------------------------------------------------------------
    // 2. Legal Subjects (assuntos)
    //    Codes and names match CNJ's Tabelas Processuais Unificadas.
    // ------------------------------------------------------------------
    const legalSubjects = [
      // Case A1 — Cível / Cobrança
      { id: 'b9000001-0001-4001-8001-b90000010001', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001', subject_code: 9985, subject_name: 'Prestação de Serviços', is_primary_subject: true },
      { id: 'b9000001-0002-4001-8001-b90000010002', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001', subject_code: 6220, subject_name: 'Inadimplemento', is_primary_subject: false },
      { id: 'b9000001-0007-4001-8001-b90000010007', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001', subject_code: 6233, subject_name: 'Indenização por Dano Material', is_primary_subject: false },
      // Case A2 — Trabalhista
      { id: 'b9000001-0003-4001-8001-b90000010003', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002', subject_code: 2034, subject_name: 'Verbas Rescisórias', is_primary_subject: true },
      { id: 'b9000001-0004-4001-8001-b90000010004', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002', subject_code: 2547, subject_name: 'Horas Extras', is_primary_subject: false },
      { id: 'b9000001-0008-4001-8001-b90000010008', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002', subject_code: 1045, subject_name: 'Adicional de Insalubridade', is_primary_subject: false },
      // Case A3 — Criminal
      { id: 'b9000001-0005-4001-8001-b90000010005', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0003-4001-8001-b80000010003', subject_code: 3399, subject_name: 'Estelionato', is_primary_subject: true },
      { id: 'b9000001-0006-4001-8001-b90000010006', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0003-4001-8001-b80000010003', subject_code: 3536, subject_name: 'Crimes contra o Patrimônio', is_primary_subject: false },
      // Case B1 — Usucapião
      { id: 'b9000002-0001-4001-8001-b90000020001', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0001-4001-8001-b80000020001', subject_code: 10432, subject_name: 'Usucapião Extraordinária', is_primary_subject: true },
      { id: 'b9000002-0002-4001-8001-b90000020002', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0001-4001-8001-b80000020001', subject_code: 10433, subject_name: 'Direitos Reais sobre Imóveis', is_primary_subject: false },
      // Case B2 — Tributário
      { id: 'b9000002-0003-4001-8001-b90000020003', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002', subject_code: 7770, subject_name: 'IRPJ/CSLL', is_primary_subject: true },
      { id: 'b9000002-0004-4001-8001-b90000020004', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002', subject_code: 7778, subject_name: 'Auto de Infração', is_primary_subject: false },
      { id: 'b9000002-0005-4001-8001-b90000020005', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002', subject_code: 6130, subject_name: 'Multa Tributária', is_primary_subject: false },
    ];
    r = await upsertRows(supabase, 'datajud_legal_subjects', legalSubjects);
    if (r.error) throw new Error(`datajud_legal_subjects: ${r.error.message}`);
    total += r.count;
    log(`datajud_legal_subjects: ${r.count} rows`);

    // ------------------------------------------------------------------
    // 3. Case Participants
    // ------------------------------------------------------------------
    const participants = [
      // Case A1 — Cobrança
      { id: 'ba000001-0001-4001-8001-ba0000010001', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001', participant_name: 'Construtora Horizonte Ltda', participant_cpf_cnpj: '44.555.666/0001-77', participant_type: 'J', case_role: 'ativo', participation_type: 'Autor', matched_contact_id: 'cf000001-0004-4001-8001-cf0000010004', match_confidence: 0.95 },
      { id: 'ba000001-0002-4001-8001-ba0000010002', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001', participant_name: 'XYZ Empreendimentos S.A.', participant_cpf_cnpj: '88.999.000/0001-22', participant_type: 'J', case_role: 'passivo', participation_type: 'Réu' },
      // Case A2 — Trabalhista
      { id: 'ba000001-0003-4001-8001-ba0000010003', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002', participant_name: 'Juliana Ferreira da Silva', participant_cpf_cnpj: '234.567.890-11', participant_type: 'F', case_role: 'ativo', participation_type: 'Reclamante', matched_contact_id: 'cf000001-0002-4001-8001-cf0000010002', match_confidence: 0.97 },
      { id: 'ba000001-0004-4001-8001-ba0000010004', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002', participant_name: 'Empresa ABC Serviços Ltda', participant_cpf_cnpj: '66.777.888/0001-33', participant_type: 'J', case_role: 'passivo', participation_type: 'Reclamada' },
      // Case A3 — Criminal
      { id: 'ba000001-0005-4001-8001-ba0000010005', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0003-4001-8001-b80000010003', participant_name: 'Ministério Público do Estado de São Paulo', participant_type: 'J', case_role: 'ativo', participation_type: 'Autor' },
      { id: 'ba000001-0006-4001-8001-ba0000010006', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0003-4001-8001-b80000010003', participant_name: 'Ricardo de Almeida', participant_cpf_cnpj: '345.678.901-22', participant_type: 'F', case_role: 'passivo', participation_type: 'Réu', matched_contact_id: 'cf000001-0003-4001-8001-cf0000010003', match_confidence: 0.98 },
      // Case B1 — Usucapião
      { id: 'ba000002-0001-4001-8001-ba0000020001', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0001-4001-8001-b80000020001', participant_name: 'Carlos Mendes da Silva', participant_cpf_cnpj: '987.654.321-00', participant_type: 'F', case_role: 'ativo', participation_type: 'Requerente', matched_contact_id: 'b5b5b5b5-0001-0001-0001-b5b5b5b5b5b5', match_confidence: 0.96 },
      { id: 'ba000002-0002-4001-8001-ba0000020002', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0001-4001-8001-b80000020001', participant_name: 'Herdeiros de João da Silva (espólio)', participant_type: 'F', case_role: 'passivo', participation_type: 'Requerido' },
      // Case B2 — Tributário
      { id: 'ba000002-0003-4001-8001-ba0000020003', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002', participant_name: 'Imobiliária Carioca Ltda', participant_cpf_cnpj: '22.333.444/0001-55', participant_type: 'J', case_role: 'ativo', participation_type: 'Impetrante', matched_contact_id: 'ce000001-0005-4001-8001-ce0000010005', match_confidence: 0.94 },
      { id: 'ba000002-0004-4001-8001-ba0000020004', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002', participant_name: 'Delegado da Receita Federal do Brasil no RJ', participant_type: 'J', case_role: 'passivo', participation_type: 'Impetrado' },
    ];
    r = await upsertRows(supabase, 'datajud_case_participants', participants);
    if (r.error) throw new Error(`datajud_case_participants: ${r.error.message}`);
    total += r.count;
    log(`datajud_case_participants: ${r.count} rows`);

    // ------------------------------------------------------------------
    // 4. Timeline Events
    //    movement_id uses composite format: "{codigo}_{dataHora}"
    //    (matches what the enrichment service generates from real API data)
    // ------------------------------------------------------------------
    const events = [
      // ── Case A1: Cível — 5 events ──────────────────────────────────
      { id: 'bb000001-0001-4001-8001-bb0000010001', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001',
        movement_id: `26_${timestampAt(-120, 9, 30)}`, movement_code: 26, movement_name: 'Distribuição', movement_complement: 'Distribuído por sorteio — 5ª Vara Cível',
        event_datetime: timestampAt(-120, 9, 30), responsible_type_code: 1, responsible_type_name: 'Servidor', responsible_code: 1001, responsible_name: 'Sistema SAJ',
        event_category: 'filing', priority_level: 'high', is_relevant: true, is_visible_client: true, is_visible_timeline: true, custom_description: 'Processo distribuído para a 5ª Vara Cível' },

      { id: 'bb000001-0002-4001-8001-bb0000010002', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001',
        movement_id: `12_${timestampAt(-95, 14, 20)}`, movement_code: 12, movement_name: 'Citação', movement_complement: 'Citação positiva via oficial de justiça',
        event_datetime: timestampAt(-95, 14, 20), responsible_type_code: 3, responsible_type_name: 'Oficial de Justiça', responsible_code: 3001, responsible_name: 'OJ da 5ª Vara Cível',
        event_category: 'notification', priority_level: 'high', is_relevant: true, is_visible_client: true, is_visible_timeline: true },

      { id: 'bb000001-0003-4001-8001-bb0000010003', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001',
        movement_id: `193_${timestampAt(-80, 10, 0)}`, movement_code: 193, movement_name: 'Juntada de Petição', movement_complement: 'Contestação do réu juntada aos autos',
        event_datetime: timestampAt(-80, 10, 0), responsible_type_code: 1, responsible_type_name: 'Servidor',
        event_category: 'filing', priority_level: 'normal', is_relevant: true, is_visible_client: true, is_visible_timeline: true },

      { id: 'bb000001-0004-4001-8001-bb0000010004', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001',
        movement_id: `3_${timestampAt(-30, 16, 45)}`, movement_code: 3, movement_name: 'Despacho', movement_complement: 'Designada audiência de conciliação',
        event_datetime: timestampAt(-30, 16, 45), responsible_type_code: 2, responsible_type_name: 'Magistrado', responsible_code: 2001, responsible_name: 'Dr. Fernando Alves',
        event_category: 'decision', priority_level: 'high', is_relevant: true, is_visible_client: true, is_visible_timeline: true, custom_description: 'Juiz designou audiência de conciliação' },

      { id: 'bb000001-0005-4001-8001-bb0000010005', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0001-4001-8001-b80000010001',
        movement_id: `970_${timestampAt(-3, 14, 0)}`, movement_code: 970, movement_name: 'Audiência Realizada', movement_complement: 'Audiência de conciliação realizada — partes não chegaram a acordo',
        event_datetime: timestampAt(-3, 14, 0), responsible_type_code: 2, responsible_type_name: 'Magistrado', responsible_code: 2001, responsible_name: 'Dr. Fernando Alves',
        event_category: 'hearing', priority_level: 'critical', is_relevant: true, is_visible_client: true, is_visible_timeline: true, custom_description: 'Audiência de conciliação — sem acordo entre as partes' },

      // ── Case A2: Trabalhista — 5 events ────────────────────────────
      { id: 'bb000001-0006-4001-8001-bb0000010006', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002',
        movement_id: `26_${timestampAt(-90, 8, 15)}`, movement_code: 26, movement_name: 'Distribuição', movement_complement: 'Reclamação trabalhista distribuída por sorteio',
        event_datetime: timestampAt(-90, 8, 15), responsible_type_code: 1, responsible_type_name: 'Servidor', responsible_name: 'Sistema PJe',
        event_category: 'filing', priority_level: 'normal', is_relevant: true, is_visible_client: true, is_visible_timeline: true },

      { id: 'bb000001-0007-4001-8001-bb0000010007', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002',
        movement_id: `1079_${timestampAt(-70, 11, 30)}`, movement_code: 1079, movement_name: 'Expedição de Notificação', movement_complement: 'Notificação postal expedida à empresa reclamada',
        event_datetime: timestampAt(-70, 11, 30), responsible_type_code: 1, responsible_type_name: 'Servidor', responsible_name: 'Maria Aparecida Santos',
        event_category: 'notification', priority_level: 'normal', is_relevant: true, is_visible_client: true, is_visible_timeline: true },

      { id: 'bb000001-0008-4001-8001-bb0000010008', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002',
        movement_id: `193_${timestampAt(-50, 9, 45)}`, movement_code: 193, movement_name: 'Juntada de Petição', movement_complement: 'Defesa da reclamada protocolada',
        event_datetime: timestampAt(-50, 9, 45), responsible_type_code: 1, responsible_type_name: 'Servidor',
        event_category: 'filing', priority_level: 'low', is_relevant: false, is_visible_client: true, is_visible_timeline: true },

      { id: 'bb000001-0009-4001-8001-bb0000010009', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002',
        movement_id: `11009_${timestampAt(-20, 15, 0)}`, movement_code: 11009, movement_name: 'Audiência Designada', movement_complement: 'Audiência inaugural designada para instrução e julgamento',
        event_datetime: timestampAt(-20, 15, 0), responsible_type_code: 2, responsible_type_name: 'Magistrado', responsible_name: 'Dra. Carla Beatriz Moreira',
        event_category: 'hearing', priority_level: 'critical', is_relevant: true, is_visible_client: true, is_visible_timeline: true, custom_description: 'Audiência de instrução e julgamento designada' },

      { id: 'bb000001-0010-4001-8001-bb0000010010', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0002-4001-8001-b80000010002',
        movement_id: `970_${timestampAt(-5, 13, 30)}`, movement_code: 970, movement_name: 'Audiência Realizada', movement_complement: 'Audiência inaugural realizada — oitiva de testemunhas concluída, sem acordo',
        event_datetime: timestampAt(-5, 13, 30), responsible_type_code: 2, responsible_type_name: 'Magistrado', responsible_name: 'Dra. Carla Beatriz Moreira',
        event_category: 'hearing', priority_level: 'critical', is_relevant: true, is_visible_client: true, is_visible_timeline: true, custom_description: 'Audiência realizada — aguardando sentença' },

      // ── Case A3: Criminal — 4 events ───────────────────────────────
      { id: 'bb000001-0011-4001-8001-bb0000010011', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0003-4001-8001-b80000010003',
        movement_id: `385_${timestampAt(-60, 10, 0)}`, movement_code: 385, movement_name: 'Recebimento da Denúncia', movement_complement: 'Denúncia do Ministério Público recebida pelo juízo',
        event_datetime: timestampAt(-60, 10, 0), responsible_type_code: 2, responsible_type_name: 'Magistrado', responsible_name: 'Dr. Marcos Vinícius Costa',
        event_category: 'decision', priority_level: 'critical', is_relevant: true, is_visible_client: false, is_visible_timeline: true, custom_description: 'Denúncia recebida — réu citado para resposta' },

      { id: 'bb000001-0012-4001-8001-bb0000010012', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0003-4001-8001-b80000010003',
        movement_id: `12_${timestampAt(-45, 9, 0)}`, movement_code: 12, movement_name: 'Citação do Réu', movement_complement: 'Citação pessoal do acusado para apresentar defesa',
        event_datetime: timestampAt(-45, 9, 0), responsible_type_code: 3, responsible_type_name: 'Oficial de Justiça',
        event_category: 'notification', priority_level: 'high', is_relevant: true, is_visible_client: false, is_visible_timeline: true },

      { id: 'bb000001-0013-4001-8001-bb0000010013', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0003-4001-8001-b80000010003',
        movement_id: `193_${timestampAt(-30, 16, 30)}`, movement_code: 193, movement_name: 'Resposta à Acusação', movement_complement: 'Resposta à acusação apresentada pela defesa',
        event_datetime: timestampAt(-30, 16, 30), responsible_type_code: 1, responsible_type_name: 'Servidor',
        event_category: 'filing', priority_level: 'normal', is_relevant: true, is_visible_client: false, is_visible_timeline: true },

      { id: 'bb000001-0014-4001-8001-bb0000010014', law_firm_id: FIRM_A_ID, datajud_case_detail_id: 'b8000001-0003-4001-8001-b80000010003',
        movement_id: `25_${timestampAt(-2, 11, 0)}`, movement_code: 25, movement_name: 'Conclusão para Decisão', movement_complement: 'Autos conclusos ao juiz para absolvição sumária ou designação de audiência',
        event_datetime: timestampAt(-2, 11, 0), responsible_type_code: 1, responsible_type_name: 'Servidor',
        event_category: 'general', priority_level: 'high', is_relevant: true, is_visible_client: false, is_visible_timeline: true, custom_description: 'Processo concluso — aguardando decisão do juiz' },

      // ── Case B1: Usucapião — 4 events ──────────────────────────────
      { id: 'bb000002-0001-4001-8001-bb0000020001', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0001-4001-8001-b80000020001',
        movement_id: `26_${timestampAt(-90, 10, 30)}`, movement_code: 26, movement_name: 'Distribuição',
        event_datetime: timestampAt(-90, 10, 30), responsible_type_code: 1, responsible_type_name: 'Servidor', responsible_name: 'Sistema PJe',
        event_category: 'filing', priority_level: 'normal', is_relevant: true, is_visible_client: true, is_visible_timeline: true, custom_description: 'Ação de usucapião distribuída' },

      { id: 'bb000002-0002-4001-8001-bb0000020002', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0001-4001-8001-b80000020001',
        movement_id: `12_${timestampAt(-60, 15, 0)}`, movement_code: 12, movement_name: 'Edital de Citação', movement_complement: 'Citação por edital dos réus incertos e desconhecidos — prazo de 20 dias',
        event_datetime: timestampAt(-60, 15, 0), responsible_type_code: 1, responsible_type_name: 'Servidor',
        event_category: 'notification', priority_level: 'high', is_relevant: true, is_visible_client: true, is_visible_timeline: true },

      { id: 'bb000002-0003-4001-8001-bb0000020003', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0001-4001-8001-b80000020001',
        movement_id: `581_${timestampAt(-15, 9, 30)}`, movement_code: 581, movement_name: 'Perícia Designada', movement_complement: 'Perícia técnica de engenharia civil designada para avaliação do imóvel',
        event_datetime: timestampAt(-15, 9, 30), responsible_type_code: 2, responsible_type_name: 'Magistrado', responsible_name: 'Dr. Antônio Carlos Duarte',
        event_category: 'general', priority_level: 'high', is_relevant: true, is_visible_client: true, is_visible_timeline: true, custom_description: 'Perícia no imóvel designada pelo juízo' },

      { id: 'bb000002-0004-4001-8001-bb0000020004', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0001-4001-8001-b80000020001',
        movement_id: `60_${timestampAt(-4, 16, 0)}`, movement_code: 60, movement_name: 'Expedição de Mandado', movement_complement: 'Mandado de constatação expedido ao oficial de justiça',
        event_datetime: timestampAt(-4, 16, 0), responsible_type_code: 1, responsible_type_name: 'Servidor',
        event_category: 'notification', priority_level: 'normal', is_relevant: true, is_visible_client: true, is_visible_timeline: true },

      // ── Case B2: Tributário Federal — 5 events ─────────────────────
      { id: 'bb000002-0005-4001-8001-bb0000020005', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002',
        movement_id: `26_${timestampAt(-30, 8, 0)}`, movement_code: 26, movement_name: 'Distribuição', movement_complement: 'Mandado de segurança distribuído à 6ª Vara Federal',
        event_datetime: timestampAt(-30, 8, 0), responsible_type_code: 1, responsible_type_name: 'Servidor', responsible_name: 'Sistema eProc',
        event_category: 'filing', priority_level: 'high', is_relevant: true, is_visible_client: true, is_visible_timeline: true, custom_description: 'Mandado de segurança contra auto de infração' },

      { id: 'bb000002-0006-4001-8001-bb0000020006', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002',
        movement_id: `193_${timestampAt(-29, 9, 20)}`, movement_code: 193, movement_name: 'Juntada de Petição Inicial', movement_complement: 'Petição inicial com pedido de liminar protocolada',
        event_datetime: timestampAt(-29, 9, 20), responsible_type_code: 1, responsible_type_name: 'Servidor',
        event_category: 'filing', priority_level: 'normal', is_relevant: true, is_visible_client: true, is_visible_timeline: true },

      { id: 'bb000002-0007-4001-8001-bb0000020007', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002',
        movement_id: `25_${timestampAt(-22, 14, 10)}`, movement_code: 25, movement_name: 'Conclusão para Decisão', movement_complement: 'Autos conclusos para análise do pedido de liminar',
        event_datetime: timestampAt(-22, 14, 10), responsible_type_code: 1, responsible_type_name: 'Servidor',
        event_category: 'general', priority_level: 'normal', is_relevant: false, is_visible_client: true, is_visible_timeline: true },

      { id: 'bb000002-0008-4001-8001-bb0000020008', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002',
        movement_id: `3_${timestampAt(-18, 17, 30)}`, movement_code: 3, movement_name: 'Despacho / Decisão', movement_complement: 'LIMINAR DEFERIDA — Suspensa a exigibilidade do crédito tributário (art. 151, IV, CTN)',
        event_datetime: timestampAt(-18, 17, 30), responsible_type_code: 2, responsible_type_name: 'Magistrado', responsible_code: 3613, responsible_name: 'Dr. Roberto Fernandes Leão',
        event_category: 'decision', priority_level: 'critical', is_relevant: true, is_visible_client: true, is_visible_timeline: true, custom_description: 'LIMINAR CONCEDIDA — Crédito tributário suspenso' },

      { id: 'bb000002-0009-4001-8001-bb0000020009', law_firm_id: FIRM_B_ID, datajud_case_detail_id: 'b8000002-0002-4001-8001-b80000020002',
        movement_id: `1079_${timestampAt(-1, 10, 0)}`, movement_code: 1079, movement_name: 'Notificação da Autoridade Coatora', movement_complement: 'Delegado da Receita Federal notificado para prestar informações em 10 dias',
        event_datetime: timestampAt(-1, 10, 0), responsible_type_code: 1, responsible_type_name: 'Servidor',
        event_category: 'notification', priority_level: 'normal', is_relevant: true, is_visible_client: true, is_visible_timeline: true },
    ];
    r = await upsertRows(supabase, 'datajud_timeline_events', events);
    if (r.error) throw new Error(`datajud_timeline_events: ${r.error.message}`);
    total += r.count;
    log(`datajud_timeline_events: ${r.count} rows`);

    // ------------------------------------------------------------------
    // 5. Sync Log — recent enrichment activity
    // ------------------------------------------------------------------
    const syncLogs = [
      // Firm A — full sync (7 days ago) + incremental (yesterday)
      {
        id: 'bc000001-0001-4001-8001-bc0000010001', law_firm_id: FIRM_A_ID,
        sync_type: 'full', sync_status: 'completed',
        total_cases_processed: 3, successful_cases: 3, failed_cases: 0,
        started_at: daysAgo(7, 2), completed_at: daysAgo(7, 2),
        duration_seconds: 38, api_calls_made: 3, rate_limit_hits: 0,
        summary: { cases_enriched: 3, timeline_events_added: 14, participants_added: 6, legal_subjects_added: 8, conflicts_detected: 1 },
        initiated_by: A.admin,
      },
      {
        id: 'bc000001-0002-4001-8001-bc0000010002', law_firm_id: FIRM_A_ID,
        sync_type: 'incremental', sync_status: 'completed',
        total_cases_processed: 3, successful_cases: 2, failed_cases: 0,
        started_at: daysAgo(1, 3), completed_at: daysAgo(1, 3),
        duration_seconds: 18, api_calls_made: 3, rate_limit_hits: 0,
        summary: { cases_enriched: 2, timeline_events_added: 2, participants_added: 0, legal_subjects_added: 0, conflicts_detected: 0 },
        initiated_by: A.admin,
      },
      // Firm B — full sync (3 days ago) + manual case-specific (today)
      {
        id: 'bc000002-0001-4001-8001-bc0000020001', law_firm_id: FIRM_B_ID,
        sync_type: 'full', sync_status: 'completed',
        total_cases_processed: 2, successful_cases: 2, failed_cases: 0,
        started_at: daysAgo(3, 1), completed_at: daysAgo(3, 1),
        duration_seconds: 25, api_calls_made: 2, rate_limit_hits: 0,
        summary: { cases_enriched: 2, timeline_events_added: 9, participants_added: 4, legal_subjects_added: 5, conflicts_detected: 0 },
        initiated_by: B.admin,
      },
      {
        id: 'bc000002-0002-4001-8001-bc0000020002', law_firm_id: FIRM_B_ID,
        sync_type: 'case_specific', sync_status: 'completed',
        matter_id: 'b0000001-0003-4001-8001-b00000010003',
        total_cases_processed: 1, successful_cases: 1, failed_cases: 0,
        started_at: daysAgo(0, 6), completed_at: daysAgo(0, 6),
        duration_seconds: 8, api_calls_made: 1, rate_limit_hits: 0,
        summary: { cases_enriched: 1, timeline_events_added: 1, participants_added: 0, legal_subjects_added: 0, conflicts_detected: 0 },
        initiated_by: B.admin,
      },
    ];
    r = await replaceRows(supabase, 'datajud_sync_log', 'law_firm_id', [FIRM_A_ID, FIRM_B_ID], syncLogs);
    if (r.error) throw new Error(`datajud_sync_log: ${r.error.message}`);
    total += r.count;
    log(`datajud_sync_log: ${r.count} rows`);

    return { module: mod, success: true, count: total };
  } catch (err) {
    return { module: mod, success: false, count: total, error: err.message };
  }
}
